#coding=utf-8
'''
python 中 一个字符串相对应一个字符数组
'''
name='abcdefghij中文'
print("name=%s"%name)
print()
print("name[0]=%s"%name[0])
print("name[1]=%s"%name[1])
print("name[len(name)-1]=%s"%name[len(name)-1])
print("name[-1]=%s"%name[-1])
print("name[-5]=%s"%name[-5])
'''
字符串切片
'''
print("name[2:4]=%s"%name[2:4])#包头不包尾
print("name[0:-2]=%s"%name[0:-2])#包头不包尾
print("name[1:6]=%s"%name[1:6])
print("name[:6]=%s"%name[:6])
print("name[:3]=%s"%name[:3])
print("name[2:]=%s"%name[2:])
print("name[0:]=%s"%name[0:])

#跳跃取
print("name[1:-1:2]=%s"%name[1:-1:2])#跳跃单位为2
print("name[1:-1:3]=%s"%name[1:-1:3])#跳跃单位为3
print("name[::2]=%s"%name[::2])#取出基数个
print("name[1::2]=%s"%name[1::2])#取出偶数个
#print("name[::0]=%s"%name[::0])
print("name[-2:-5:-1]=%s"%name[-2:-5:-1])
#倒序name
print("name[::-1]=%s"%name[::-1])
